# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=member.models.image_location)),
                ('phd', models.CharField(blank=True, max_length=120, null=True)),
                ('ms', models.CharField(blank=True, max_length=120, null=True)),
                ('bs', models.CharField(blank=True, max_length=120, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.TextField(blank=True, null=True)),
                ('homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('graduation', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('Research Professor', 'Research Professor'), ('Post Doctoral Fellow', 'Post Doctoral Fellow'), ('Ph.D. Candidate', 'Ph.D. Candidate'), ('Master Candidate', 'Master Candidate'), ('Staff', 'Staff'), ('Alumni', 'Alumni')], default='Master Candidate', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
