# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161031_0418'),
        ('member', '0002_auto_20161102_0909'),
    ]

    operations = [
    ]
