# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='paper_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=protocol.models.image_location),
        ),
    ]
