# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import protocol.models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_auto_20161102_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=protocol.models.image_location),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal Club'), ('paper', 'Paper Presentation'), ('protocol', 'Protocols'), ('lecture', '\uc9c0\uc2dd\uc7ac\uc0b0\ub300\ud559\uc6d0\ud2b9\uac15')], default='journal', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=protocol.models.video_location),
        ),
    ]
