# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_merge_20161102_0042'),
        ('protocol', '0003_auto_20161102_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolPresenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='presenter',
        ),
        migrations.AddField(
            model_name='protocolpresenter',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol.Protocol'),
        ),
    ]
