# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_auto_20161102_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
