# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0005_auto_20161102_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='korean',
            field=models.URLField(blank=True, null=True),
        ),
    ]
