# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('notice', 'notice'), ('news', 'news')], default='notice', max_length=120),
        ),
    ]
