# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('journal', 'journal'), ('patents', 'patents'), ('conference', 'conference'), ('book', 'book')], default='journal', max_length=120)),
                ('author', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.CharField(blank=True, max_length=120, null=True)),
                ('patent', models.CharField(blank=True, max_length=120, null=True)),
                ('conference', models.CharField(blank=True, max_length=120, null=True)),
                ('book', models.CharField(blank=True, max_length=120, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
