# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='poeple',
            field=models.ManyToManyField(through='publication.PublicationItem', to='member.Member'),
        ),
    ]
